apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: cluster-port
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: redis
    appCluster: redis-cluster
  sessionAffinity: None
  type: ClusterIP
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: redis-cluster