apiVersion: v1
kind: ServiceAccount
metadata:
  name: modify-pods-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: modify-pods-sa
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
